### ISSUE TITLE
Conseguir background para vista principal

### ISSUE THREAD

**Issue by castrogarciajs** [castrogarciajs/merch#11]

**Comment by castrogarciajs** [comment]
Hola team,

Porfavor conseguir una imagen para la vista principal de la tienda

## example

![2023-10-20 (3)](https://github.com/castrogarciajs/merch/assets/116913262/dfda4dc6-f4a6-4653-835e-6c3deef9ad30)

**Comment by Jhonjandrysdev** [comment]
- Me tome la tarea de diseñar un banner para esa parte, tu me dirás si esta optimo o se busca otra opción.
![Banner Tienda Mascotas Moderno Naranja Azul](https://github.com/castrogarciajs/merch/assets/115559419/454d9047-4c11-46bd-981a-2917ef66c874)

**Comment by Jhonjandrysdev** [comment]
Se creo la tarea  #11

**Comment by castrogarciajs** [comment]
Exelente!
