### ISSUE TITLE
Eliminar problema al remover productos del carrito de compras

### ISSUE THREAD

**Issue by santiagoRicops** [castrogarciajs/merch#19]
screenshot:
![imagen_2023-11-15_165249503](https://github.com/castrogarciajs/merch/assets/142063104/7004bfdb-4f09-4c7c-b258-eccc156e640c)

Este bug surge después de agregar un producto al carrito por primera vez. Al vaciar el carrito e intentar seleccionar un nuevo artículo, aparece una alerta indicando que se ha eliminado un producto del carrito.

**Comment by castrogarciajs** [comment]
Thanks!
